name: Continuous Integration*

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Оновлюємо до версії v4

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission to mvnw
      run: chmod +x mvnw

    - name: Install dependencies and build project
      run: |
        ./mvnw clean package
        
    - name: Run unit tests
      run: |
        # Команди для виконання модульних тестів
        
  create_branch_and_pull_request:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.event.action == 'opened' || github.event.action == 'synchronize'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
      with:
        ref: ${{ github.head_ref }}

    - name: Create new branch
      run: |
        git checkout -b my-new-branch
        
    - name: Make changes to the code
      run: |
        
    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update project code"

    - name: Push changes to new branch
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: my-new-branch

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Create pull request'
        title: 'Update project code'
        branch: my-new-branch
        base: main
